ManageBlog/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.getListBlogDefault),
    re_path(
        r'^sort=(?P<typeSort>[-\s\S]+|())&page_id=(?P<pageNumber>[\d]+|())/$', views.getListBlog_WithNumberPage),
    re_path(
        r'^search=(?P<title>[-\s\S]+|())&page_id=(?P<pageNumber>[\d]+|())/$', views.searchBlogWithTitle),
    path('<str:urlBlog>', views.getBlogByURL),
    path('<str:urlBlogNeedEdit>/chinh-sua/', views.editBlog),
    path('xuat-ban/', views.postBlog)
]

ban/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ban),
]

jsClub_Forum/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),

    re_path(r'^static/(?P<path>.*)$', serve,
            {'document_root': settings.STATIC_ROOT}),
    path('', include('home.urls')),
    path('ban/', include('ban.urls')),
    path('su-kien/', include('event.urls')),
    path('bai-dang/', include('ManageBlog.urls')),
    path('froala_editor/', include('froala_editor.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'jsClub_Forum.views.custom_error_404'

ManageBlog/models.py
from django.db import models
from froala_editor.fields import FroalaField

URL_IMAGE_THUMBNAIL_BLOG_DEFAULT = 'uploads/image/blogThumbnailDefault.png'
SET_BLOG_STATUS = {
    ('STATUS_Pending', 'Pending'),
    ('STATUS_Approve', 'Approve')
}


class Blog(models.Model):
    title = models.CharField(max_length=160)  # min = 10
    thumbnail = models.ImageField(
        default=URL_IMAGE_THUMBNAIL_BLOG_DEFAULT)
    urlBlog = models.CharField(unique=True, max_length=200)
    description = models.TextField(max_length=250)
    content = FroalaField(blank=True, null=True)
    countViewer = models.IntegerField(default=0)
    status = models.CharField(
        choices=SET_BLOG_STATUS,
        default='STATUS_Pending',
        max_length=20)
    dateTime = models.DateTimeField(auto_now_add=True, editable=False)

    def __str__(self):
        return self.title

ManageBlog/forms.py
from dataclasses import field
from django import forms
from django.contrib import admin
from froala_editor.widgets import FroalaEditor
from .models import Blog


class BlogForm(forms.ModelForm):

    # content = forms.CharField(widget=FroalaEditor)

    class Meta:
        model = Blog
        fields = {'title', 'description', 'content'}

ManageBlog/views.py
from django.shortcuts import render
from .forms import BlogForm
from .models import Blog
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from .inputProcess import *


def getListBlogDefault(request):
    return HttpResponseRedirect(URL_GET_LIST_BLOG_DEFAULT)


def getListBlogWithPagination(queryBlog, pageNumber):
    paginator_page = Paginator(queryBlog, NUMBER_BLOG_IN_ONE_PAGE)
    pageNumber = int(pageNumber)
    if pageNumber > paginator_page.num_pages:
        pageNumber = paginator_page.num_pages

    try:
        page_obj = paginator_page.get_page(pageNumber)
        indexPage = pageNumber
    except PageNotAnInteger:
        page_obj = paginator_page.get_page(1)
        indexPage = 1
    except EmptyPage:
        page_obj = paginator_page.page(paginator_page.num_pages)
        indexPage = paginator_page.num_pages

    data = {'page_obj': page_obj,
            'totalPages': paginator_page.num_pages,
            'indexPage': indexPage,
            'status': 'Found'}

    return data


def getListBlog_WithNumberPage(request, typeSort, pageNumber):
    queryBlog = Blog.objects.filter(
        status=DIC_BLOG_STATUS['STATUS_Approve']).order_by('-dateTime')
    if request.method == 'GET':
        if typeSort == TYPE_SORT_BLOG[0]:
            queryBlog = Blog.objects.filter(
                status=DIC_BLOG_STATUS['STATUS_Approve']).order_by('-dateTime')
        elif typeSort == TYPE_SORT_BLOG[1]:
            queryBlog = Blog.objects.filter(
                status=DIC_BLOG_STATUS['STATUS_Approve']).order_by('-countViewer')
        else:
            return HttpResponseRedirect('/bai-dang/sort=' + TYPE_SORT_BLOG[0] + '&page_id=1/')
    if len(pageNumber) != 0:
        data = getListBlogWithPagination(queryBlog, pageNumber)
        if int(pageNumber) > data.get('totalPages'):
            return HttpResponseRedirect('/bai-dang/sort=' + typeSort + '&page_id=' + str(data.get('totalPages')) + '/')
        return render(request, TEMPLATE_DISPLAY_LIST_BLOG, data)
    return HttpResponseRedirect('/bai-dang/sort=' + typeSort + '&page_id=1/')


def searchBlogWithTitle(request, title, pageNumber):
    if len(pageNumber) == 0:
        return HttpResponseRedirect('/bai-dang/search=' + title + '&page_id=1/')
    queryBlogSearch = Blog.objects.filter(
        title__contains=title, status=DIC_BLOG_STATUS['STATUS_Approve'])
    if queryBlogSearch.exists():
        data = getListBlogWithPagination(queryBlogSearch, pageNumber)
        totalPage = data.get('totalPages')
        if int(pageNumber) > totalPage:
            return HttpResponseRedirect('/bai-dang/search=' + title + '&page_id=' + str(totalPage) + '/')
        return render(request, TEMPLATE_DISPLAY_LIST_BLOG, data)
    else:
        return render(request, TEMPLATE_DISPLAY_LIST_BLOG, {'status': title + ' Not Found'})


def getBlogByURL(request, urlBlog):
    blog = Blog.objects.filter(
        urlBlog=urlBlog, status=DIC_BLOG_STATUS['STATUS_Approve'])
    if blog.exists():
        newView = blog.first().countViewer + 1
        blog.update(countViewer=newView)
        return render(request, TEMPLATE_DISPLAY_SPECIFIC_BLOG, {'data': blog.values, 'status': 'Found'})
    else:
        return render(request, TEMPLATE_DISPLAY_SPECIFIC_BLOG, {'status': 'Not Found'})


def saveBlogIntoDatabase(inputTitle, intputURL, inputDescription, inputContent, inputURLImage):
    newBlog = Blog.objects.create(title=inputTitle,
                                  urlBlog=intputURL,
                                  description=inputDescription,
                                  content=inputContent,
                                  thumbnail=inputURLImage)
    newBlog.save


def checkURLIsUnique(urlNeedCheck):
    return Blog.objects.filter(urlBlog=urlNeedCheck).exists()


def makeNewBlog(formValid):
    title = formValid.cleaned_data['title']

    urlCreate = createURLFromTitleBlog(title)
    while checkURLIsUnique(urlCreate):
        urlCreate = createURLFromTitleBlog(title)
    description = formValid.cleaned_data['description']
    content = formValid.cleaned_data['content']
    urlBlog = urlCreate
    URLImageBlog = getFirstImageInContentBlog(content)
    saveBlogIntoDatabase(title, urlBlog, description, content, URLImageBlog)

def editBlog(request, urlBlogNeedEdit):
    try:
        blogNeedEdit = Blog.objects.get(
            urlBlog=urlBlogNeedEdit, status=DIC_BLOG_STATUS['STATUS_Approve'])
    except Blog.DoesNotExist:
        return HttpResponseRedirect('/bai-dang/')

    if request.method == 'POST':
        form = BlogForm(request.POST, instance=blogNeedEdit)
        if form.is_valid():
            form.save()
            return render(request, TEMPLATE_STATUS,
                          {'message': 'Chỉnh sửa thành công!'})
        else:
            return render(request, TEMPLATE_STATUS,
                          {'message': 'Chỉnh sửa thất bại!'})
    elif request.method == 'GET':
        form = BlogForm(instance=blogNeedEdit)
    return render(request, TEMPLATE_DISPLAY_FORM_PUBLISH_BLOG, {'form': form})


def postBlog(request):
    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            makeNewBlog(form)
            return render(request, TEMPLATE_STATUS, {'message': 'Đăng bài thành công!'})
        else:
            return render(request, TEMPLATE_STATUS,
                          {'message': 'Đăng bài thất bại!'})
    form = BlogForm()
    return render(request, TEMPLATE_DISPLAY_FORM_PUBLISH_BLOG, {'form': form})

ManageBlog/templates/pages/blog.html
{% extends "pages/index.html" %}

{% block title %}Bài Đăng- JS Club{% endblock %}

{% block content %}
{% load static %}

<img src="{% static 'img/b_blog.png' %}" style="width:100%;padding-left: 5%;padding-right: 5%;">
<!-- <form action="" method="GET">
    {% csrf_token %} -->
<div class = "container" style="margin-top: 0px;padding-left: 0px;padding-right: 0px;">

{% comment %} <label for="fname">Search Title:</label><br> {% endcomment %}
<input class="form-control mr-sm-2" id = "myInput" type="text" name="searchTitle" style= "margin-bottom: 1%; margin-top: 2%;" placeholder="Search">
<button class="btn btn-outline-success my-2 my-sm-0" id = "myBtn" onclick="search()">Search</button>
<button class="btn btn-outline-success my-2 my-sm-0" onclick="sortBlog('date')">Sort Blog By Date</button>
<button class="btn btn-outline-success my-2 my-sm-0" onclick="sortBlog('views')">Sort Blog By Views</button>

</div>
<!-- </form> -->

<div class = "container" style="display: flex;flex-direction: row-reverse;padding-right: 0px;padding-left: 0px;">
    <button type="button" class="btn btn-primary" onclick="location.href='/bai-dang/xuat-ban/';">Đăng bài</button>
</div>

<script>
    function search() {
        var titleSearch = document.getElementsByName('searchTitle')[0].value;
        if (titleSearch.length !== 0) {
            let urlSearchEndCode = encodeURIComponent(titleSearch);
            window.location = "/bai-dang/search=" + urlSearchEndCode + "&page_id=1/";
        }

    }

    function sortBlog(type) {
        if (type == 'date') {
            window.location = "/bai-dang/sort=" + 'date' + "&page_id=1/";
        } else if (type == 'views') {
            window.location = "/bai-dang/sort=" + 'views' + "&page_id=1/";
        } else {
            window.location = "/bai-dang/sort=" + 'date' + "&page_id=1/";
        }
    }

    var input = document.getElementById("myInput");
input.addEventListener("keyup", function(event) {
  if (event.keyCode === 13) {
   event.preventDefault();
   document.getElementById("myBtn").click();
  }
});

</script>


{% comment %} <button onclick="sortBlog('date')">Sort Blog By Date</button>
<button onclick="sortBlog('views')">Sort Blog By Views</button> {% endcomment %}


<style>
    .col-list{
        padding: 0px !important;
        border: 1px solid rgb(223 223 223);
      
        width: 600px !important;
      }
      
      .list-img {
        height: 100%;
          width:100%;
      }
      
      
      .nav-img {
        border-radius: 100%;
          height: 32px;
          width: 32px
      }
      .title {
        display: inline-block;
      }
      
      .head-nav {
        margin-left: 10px;
        margin-top: 24px;
      }
      
      .row {
        justify-content: center;
        margin-bottom: 30px;
        cursor: pointer;
        box-shadow: 0px 0px 10px 0px #3a333345;;
      }
      
      .para-title{
        text-align: justify;
        margin-top: 10px;
        font-size: 1.5rem;
      }
      
      .para-detail {
        overflow: hidden;
        display: -webkit-box;
        -webkit-line-clamp: 4;
        -webkit-box-orient: vertical;
        text-align: justify;
      }
      
      .view-list {
          border-top: 1px solid #80808038;
          padding-top: 5px;
      }
      
      
      
    h3 {
        color: red;
    }

    .img_thumbnail {
        width: 300px;
    }

    .container {
        margin-top: 20px;
        
    }

    .btn-outline-success {
        color: #2076f6;
        border-color: #2076f6;
    }

    .btn-outline-success:hover {
        color: #fff;
        background-color: var(--blue);
        border-color: var(--blue);
    }

    .pagination-container {
        display: flex;
        justify-content: center;

    }

.counter { background-color: #ffffff; padding: 20px 0; border-radius: 5px;}
.count-title { font-size: 40px; font-weight: normal;  margin-top: 10px; margin-bottom: 0; text-align: center; }
.count-text { font-size: 13px; font-weight: normal;  margin-top: 10px; margin-bottom: 0; text-align: center; }
.fa-2x { margin: 0 auto; float: none; display: table; color: #4ad1e5; }

    
</style>
{% comment %} list {% endcomment %}
{% if status == 'Found' %}
<center>
    {% for blog in page_obj.object_list %}
    <div class = "container">
    <div class="row" onclick="location.href='/bai-dang/{{blog.urlBlog}}';">
        <div class="col-sm-5 col-list">
        <img class="list-img" src="/media/{{blog.thumbnail}}" alt="">
        </div>
        <div class="col-sm-7 col-list">
         <div class="container">
             <div class="nav-list">
                 <div class="head-nav">
                     <div class="title">
                         <p style="top: 7%;font-size: 70%;position: absolute;margin-bottom: 0px;left: 4%;" >{{ blog.dateTime}}</p>
                     </div>
                     <div class="para-list">
                         <h3 class="para-title"><a href="/bai-dang/{{blog.urlBlog}}"> {{ blog.title}}</a></h3></br>
                         <p class="para-detail">{{ blog.description}}</p>
                     </div>
                     <div class="view-list" >
                         <p style="line-height: 2rem;display: inline;">{{ blog.countViewer}}</p>
                         <p style="display: inline;">Views</p>
                     </div>
                 </div>
             </div>
         </div>
        </div>
    </div>
</div>
    {% endfor %}

    {% comment %} <h3>Tổng số trang: </h3>
    {{totalPages}}<br>
    <h3>Trang hiện tại: </h3>
    <p>{{indexPage}}</p>
    <br> {% endcomment %}

    <div class="container">

        <div class="row">
            <div class="col-sm" style="padding-left: 0px; padding-right: 0px">
                <div class="counter col_fourth">
                    <i class="fa fa-code fa-2x"></i>
                    <h2 class="count-text ">Tổng số trang</h2>
                    <p class="timer count-title count-number" >{{totalPages}}</p>
                  </div>
            </div>
            <div class="col-sm">
                <div class="counter col_fourth">
                    <i class="fa fa-coffee fa-2x"></i>
                    <h2 class="count-text ">Trang hiện tại</h2>
                    <p class="timer count-title count-number">{{indexPage}}</p>
                  </div>
            </div>
          </div>

        
    </div>

    <center>
        <div class = "container pagination-container">
        {% if page_obj.has_other_pages %} <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="/bai-dang/sort=date&page_id={{ page_obj.previous_page_number }}/">&laquo;</a></li>
            {% else %}
            <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
            {% endif %}

            {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
            <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="/bai-dang/sort=date&page_id={{ i }}/">{{ i }}</a></li>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item" ><a class="page-link" href="/bai-dang/sort=date&page_id={{ page_obj.next_page_number }}/">&raquo;</a></li>
            {% else %}
            <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
            {% endif %}
        </ul>
        {% endif %}
    </div>
    </center>
</center>
{%else%}

<div class = "container">
<h1>{{status}}</h1>
</div>
{% endif %}


{% endblock %}

ManageBlog/templates/pages/post.html
{% extends "pages/index.html"%}
{% block title %}{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/post.css' %}" type="text/css">
{% for blog in data %}
<div class="homee" style="padding-left: 50px; padding-right: 50px;padding-top: 65px;background: linear-gradient(to right, rgb(27, 26, 26), rgb(202, 168, 203));">
    <div class="spaces"></div>

<div class="back-blog">
    <!-- <script>
        let btnBack = document.querySelector('button');
        btnBack.addEventListener('click', () => {
        window.history.back();
     });
    </script> -->
    <button class="back-button" onclick="history.back()"><a href="#">Back</a></button>
     
</div>

<div class="blog-title">
    <h1>{{blog.title}}</h1>
</div>

<div class="luot-view">
    <h5>Lượt view: {{blog.countViewer}}</h5>
</div>

<div class="blog-content">
    {{blog.content | safe}}
</div>

{% if status == 'Found' %}
<div class="button-fixx">
    <button class="fix-button"><a href="{{blog.urlBlog}}/chinh-sua/">Chỉnh sửa</a></button>
</div>
{% endif %}

{% endfor %}
{{status}}

{% endblock %}

ManageBlog/templates/pages/postform.html
{% extends "pages/index.html"%}
{% block title %}POST_FORM{% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/postform.css' %}" type="text/css">
<div class="homee" style="padding-left: 50px; padding-right: 50px; padding-top: 65px;background: linear-gradient(to right, rgb(27, 26, 26), rgb(202, 168, 203));">
<style>
    #id_title {
        width: 80%;
        height: 50px;
        border-radius: .4rem;
        box-shadow: 5px 10px rgb(63, 48, 65);
    }

    #id_description {
        width: 100%;
        height: 100px;
        border-radius: .6rem;
        box-shadow: 5px 10px rgb(63, 48, 65);
    }
</style>
<div class="spaces"></div>
<div class="formhead">
    <h1>Blog's Form</h1>
</div>
<div class="form-part">
    <div class="container-fluid form-content">
        <form action="" method="POST">
            {% csrf_token %}
            <label class="form-lable">Title</label><br>
            {{form.title}} <br>
            <br><label class="form-lable">Description</label><br>
            <div>
                {{form.description}}
            </div> <br>
            <br><label class="form-lable">Content</label><br>
            {{form.content}} <br>
            <br>
            <input type="submit" value="Submit" class="btn btn-success">
        </form>
    </div>
</div>

{% endblock %}

ManageBlog/templates/pages/status.html
{% extends "pages/index.html" %}

{% block title %}Bài Đăng- JS Club{% endblock %}

{% block content %}
{% load static %}

<div class="status_back">
    <div class="status-part">
        <h1>{{message}}</h1>
        <button class="status_button"><a href="/bai-dang">Back</a></button>
    </div>
</div>
<style>
    .status_button{
        padding-left: 2%;
        padding-right: 2%;
        padding-top: 1%;
        padding-bottom: 1%;
        border-radius: .4rem;
        box-shadow: 2px 6px rgb(0, 0, 0);
    }
    .status_back{
        margin-top: 20%;
        margin-bottom: 20%;
    }
    .status-part{
        border-radius: .5rem;
        padding-top: 3%;
        padding-bottom: 3%;
        background-color: rgb(170, 136, 201);
        box-shadow: 2px 6px rgb(73 60 74);
        text-align: center;
        color: #fff;
        margin-left: 40px;
        margin-right: 40px;
    }
</style>

{% endblock %}